version: '3'

services:
    api:
        build:
            context: .
            dockerfile: ./docker/golang/Dockerfile
        ports:
            - "8000:8000"
        container_name: api
        depends_on:
            - postgres
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=book_list
        # volumes:
        #     - ./api:/go/src/github.com/ono5/book-list/api

    postgres:
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        container_name: db
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=book_list
