FROM node:10.13-alpine
MAINTAINER kanagawa App Developer Ltd

RUN npm uninstall -g create-react-app
RUN npm install -g create-react-app

WORKDIR ./frontend

RUN npm install --save bootstrap axios popper.js react-redux react-router-dom redux redux-api-middleware redux-thunk
